BEGIN;

CREATE TABLE baz (
  id SERIAL PRIMARY KEY,
  c VARCHAR(16)
);

CREATE TABLE foo (
  id SERIAL PRIMARY KEY,
  baz_id INTEGER NOT NULL REFERENCES baz (id),
  a VARCHAR(16)
);

CREATE TABLE bar (
  id SERIAL PRIMARY KEY,
  baz_id INTEGER NOT NULL REFERENCES baz (id),
  b VARCHAR(16)
);

COMMIT;
